#!/bin/bash
#
# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

if [ "$(ss -nt \( dport = :6667 and sport \> :1024 \) | wc -l)" -gt 1 ]
then
    echo -n "IRC sockets detected: "
    ss -nt \( dport = :6667 and sport \> :1024 \) | \
	awk '/ESTAB/ {print $5}' | \
	tr "\n" ' '
    echo
    exit 2
fi

echo "No IRC socket found"
exit 0
