#!/bin/bash
#
# Copyright (C) 2013-2015 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -u

help() {
    echo "Usage: $0 [--hostname=localhost] [--port=11211] [--timeout=5]" >&2
    echo "  [--password=foobar] [--maxmemory-threshold-percent=80]" >&2
}

# ":" means required
# "::" means optional
TEMP=$(getopt -o h: --long hostname::,port::,timeout::,password: \
	      --long maxmemory-threshold-percent:: -n "$0" -- "$@")

# Check for non-GNU getopt
if [ $? != 0 ]
then
    help
    exit 1
fi

# Default values
hostname='localhost'
port=6379
timeout=5
password=''
pass_opt=''
maxmemory_threshold_percent=80

# Parse options with getopt
eval set -- "$TEMP"
while true
do
    case "$1" in
	--hostname)
	    hostname="$2"
	    shift 2
	    ;;

	--port)
	    port="$2"
	    shift 2
	    ;;

	--timeout)
	    timeout="$2"
	    shift 2
	    ;;

	--password)
	    password="$2"
	    shift 2
	    ;;

	--maxmemory-threshold-percent)
	    maxmemory_threshold_percent="$2"
	    shift 2
	    ;;

	--)
	    shift
	    break
	    ;;

	*)
	    echo "$0: getopt error!" >&2
	    exit 1
	    ;;
    esac
done

if ! [ -z $password ]
then
	pass_opt="-a $password"
fi

redis_cli="redis-cli -h $hostname -p $port $pass_opt"

# PING Redis
if ! timeout $timeout $redis_cli ping \
	| grep -qE '^PONG$'
then
    echo 'Failed to connect Redis'
    exit 2
fi

# Fetch memory values from Redis
used_memory_peak=$($redis_cli INFO memory \
			  | awk -F":|\r" '/^used_memory_peak:/ {print $2}')
maxmemory=$($redis_cli CONFIG GET maxmemory | tail -1)

if [ "$maxmemory" != 0 ]
then
    # Check if 'used_memory_peak' is does not exceed X% of 'maxmemory' with X=80
    # by default.
    percent_memory_used=$(($used_memory_peak * 100 / $maxmemory))
    if [ "$percent_memory_used" -ge $maxmemory_threshold_percent ]
    then
	echo "${percent_memory_used}% memory used, please adjust 'maxmemory'"
	exit 2
    fi

    echo "${percent_memory_used}% memory used"
fi
exit 0
