#!/bin/bash
#
# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

offset_dir='/var/lib/nagios-plugins-cyb'
error_file='/var/log/nagios-plugins-cyb/check_log-error.log'
logfiles='/var/log/kern.log /var/log/mysql/error.log'
rule_file='/etc/nagios-plugins/config/cyb_check_log.conf'

mkdir -p $(dirname $error_file) $offset_dir

# Check new errors from logs
for logfile in $logfiles
do
    [ ! -f $logfile ] && continue

    tempfile=$(tempfile)
    trap "rm -f $tempfile" EXIT HUP INT TRAP TERM
    grep -vE '^#|^$' $rule_file > $tempfile

    logtail2 -f $logfile -o $offset_dir/$(basename $logfile).offset \
	| grep -F -f $tempfile >> $error_file || true

    rm -f $tempfile
done

# Show errors if needed
if [ -s $error_file ]
then
    echo -n "Check $error_file: "
    tr "\n" . < $error_file
    exit 2
fi

echo 'OK'
exit 0
