#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@bouthors.org>
#               2014 Michael Jeanson <michael.jeanson@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

block=$1
block2=$(echo $block | sed 's/\//_/g')
if [ -z "$block" ]
then
    echo $0 too few arguments >&2
    echo Usage: $0 IP_ADDRESS/NETMASK >&2
    exit $STATE_CRITICAL
fi

if ! echo $block|egrep '(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$' > /dev/null
then
    echo $0 $block is not a valid CIDR block
    exit $STATE_CRITICAL
fi

checkfile="/tmp/check_rbl_block_${block2}.state"
checkfile_max_age="7200"

# Set default RBLs, can be overriden in the config file
dnsbls='
    zen.spamhaus.org
    bl.spamcop.net
    cbl.abuseat.org
    b.barracudacentral.org
    ips.backscatterer.org
    '

whitelist='/etc/nagios-plugins/config/cyb_rbl.d'

lockfile="/var/lock/check_rbl_block_${block2}"

conffile="/etc/nagios-plugins/config/rbl.conf"
if [ -f "$conffile" ]
then
    . "$conffile"
fi

export dnsbls
export checkfile
export lockfile
export block


update_file() {
    if dotlockfile -r 0 -p "$lockfile"
    then
        ip_list=$(sipcalc -s 32 $block | awk '/Network/ { print $3 }')

        # Clear checkfile content
        >"${checkfile}.tmp"

        for ip in $ip_list
        do
            if ! rgrep -F -q $ip $whitelist
            then
                revip=$(echo $ip | awk -F. '{print $4"."$3"."$2"."$1}')

                for dnsbl in $dnsbls
                do
                    if host -W 10 -t A $revip.$dnsbl > /dev/null 2>/dev/null
                    then
                        echo -n "$ip blacklisted by $dnsbl " >> "${checkfile}.tmp"
                    fi
                done
            fi
        done

        mv "${checkfile}.tmp" "${checkfile}"

        # Remove lock
        dotlockfile -u "$lockfile"
    fi
}

exit_and_update () {
    # Use double backgrounding to detach from nrpe
    (update_file &) &
    exit $1
}


# File doesn't exist
if [ ! -f "$checkfile" ]
then
    echo 'OK: No output file'
    exit_and_update $STATE_OK
fi

# File is too old
checkfile_age=$(expr `date +%s` - `stat -c %Y "$checkfile"`)
if [ $checkfile_age -gt $checkfile_max_age ]; then
    echo "Output file is too old (${checkfile_age} > ${checkfile_max_age})"
    exit_and_update $STATE_CRITICAL
fi

# File is not zero size
if [ -s "$checkfile" ]
then
   cat "$checkfile"
   exit_and_update $STATE_CRITICAL
fi

echo "OK"
exit_and_update $STATE_OK
