#!/bin/bash
#
# Copyright (C) 2014 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

critical=0
host=$1
delay=$2

if [ -z "$host" -o -z "$delay" ]
then
    echo "$0 too few arguments" >&2
    echo "Usage: $0 HOST DELAY" >&2
    echo "delay is expressed in minutes" >&2
    exit 1
fi

# Check if Nagios recently launched a check

last_check_time=$(echo -e "GET services\n\r\nStats: max last_check\r\n" | nc $host 6557)
current_time=$(date +%s)
last_check_time_elapsed=$(($current_time - $last_check_time))

echo "The last Nagios check was $last_check_time_elapsed second(s) ago"

if [ "$last_check_time_elapsed" -gt "$delay" ]
then
    exit 2
fi

# Check that no service check is stuck, this sometimes happens and we need to
# know when to collect more information and fix this bug. Check that the oldest
# 'last_check' variable from /var/lib/nagios3/retention.dat is not older than 7
# days.

file='/var/lib/nagios3/retention.dat'
day=7
oldest=$(grep -E '^last_check=' $file | sort -n | head -1 | cut -d= -f2)
current_timestamp=$(date +%s)
if [ "$(($current_timestamp - $oldest / 60 * 60 * 24 * 7))" -gt $day ]
then
    echo "The oldest 'last_check' entry from $file is older than $day days, it probably means that one of the Nagios checks is stuck."
    exit 2
fi

exit 0
