#!/bin/bash
#
# Copyright (C) 2014 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

delay=$1

set -e -o pipefail -o nounset

critical=0
file='/var/log/nagios3/nagios.log'

# Check arguments
if [ -z "$delay" ]
then
    echo "$0 too few arguments"
    echo "Usage: $0 DELAY"
    echo "DELAY is expressed in seconds"
    exit 2
fi

# Check file
if [ ! -f "$file" ]
then
    echo "$0: file $file not found"
    exit 2
fi

# Check Nagios log file modification time
file_modification_time=$(find "$file" -printf "%T@\n" | cut -d. -f1)
file_modification_delay=$(($(date +%s) - $file_modification_time))

echo "$file was modified $file_modification_delay seconds ago"

if [ $file_modification_delay -gt $delay ]
then
    exit 2
fi

exit 0
