#!/bin/bash
#
# Copyright (C) 2014 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

worker=$1
app_dir=$2

set -e -o pipefail -o nounset

rc=0

# Check arguments
if [ -z "$worker" -o -z "$app_dir" ]
then
    echo "Usage: $0 WORKER APP_DIR"
    exit 3
fi

# Check if $app_dir/manage.py exists
if [ ! -e "$app_dir/manage.py" ]
then
    echo "Cannot find any manage.py file in APP_DIR variable directory"
    exit 3
fi

# Create temporary file
tempfile=$(tempfile)
trap "rm -f $tempfile" EXIT HUP INT TRAP TERM

# Ping Celery
if ! $app_dir/manage.py celery inspect ping -d $worker > $tempfile 2>&1
then
    rc=2
fi

# Match string 'pong' against Celery output
if ! grep -qF pong $tempfile
then
    rc=2
fi

# Show Celery output
tr "\n" ' ' < $tempfile

exit $rc
