#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

file='/var/lib/nagios-plugins-cyb/check_safe_browsing_bulk.out'

if ! find $file -mtime -60 2>/dev/null | grep -qF $file
then
    echo "$file is too old or does not exist"
    exit 2
fi

read rc msg < /var/lib/nagios-plugins-cyb/check_safe_browsing_bulk.out

echo "$msg"
exit $rc
