#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

smartctl='smartctl -q errorsonly'
in_progress='Self-test routine in progress'
critical=0

lockfile=/var/lock/check_smartctl
dotlockfile -r 0 -p $lockfile || exit 3

for disk in /dev/sd?
do

    if $smartctl -i $disk | grep -q 'Device does not support SMART'
    then
	continue
    fi

    # Launch a check, if not already running
    if ! smartctl -l selftest $disk | grep -q "$in_progress"
    then
	$smartctl -t short $disk
    fi

    # Wait for the test to finish
    while smartctl -l selftest $disk | grep -qE "^# 1.*$in_progress"
    do
	sleep 5
    done

    if smartctl -l selftest $disk | grep -q 'Completed: read failure'
    then
	critical=1
	echo -n "$disk: SMART error detected. "
    fi
done

dotlockfile -u $lockfile

if [ $critical = 1 ]
then
    echo
    exit 2
fi

echo OK
exit 0
