#!/bin/bash
#
# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

warning_threshold=$1
critical_threshold=$2
shift 2
excluded_paths=$*

set -e -o pipefail -u

if [ -z "$warning_threshold" -o -z "$critical_threshold" ]
then
    echo "$0: too few argument" >&2
    echo "Usage: $0 WARN_THRESHOLD CRITICAL_THRESHOLD [EXCLUDED_PATH [EXCLUDED_PATH [...]]]" >&2
    echo "Example: $0 80 90" >&2
    echo "Example: $0 80 90 /var/lib/lxc" >&2
    exit 1
fi

# Fetch disk usage data
tempfile=$(tempfile)
trap "rm -f $tempfile" EXIT HUP INT TRAP TERM

(
    # Fetch blocks information
    df -PlTh

    # Fetch inodes information
    echo 'INODES'
    df -PlThi
) > $tempfile

for pipestatus in ${PIPESTATUS[@]}
do
    if [ "$pipestatus" -ne 0 ]
    then
	echo 'Unable to create a temporary file, the disk is probably full'
	exit 2
    fi
done

rc=0
units='B'
while read fs type size used available percentage mount_point
do
    # Check if mount point exists
    if [ "$fs" = 'Filesystem' ]
    then
	continue
    fi

    if [ "$fs" = 'INODES' ]
    then
	units=' inodes'
	continue
    fi

    # Check if we are in the an excluded path
    for excluded_path in $excluded_paths
    do
	if echo $mount_point | grep -qE "^$excluded_path"
	then
	    continue 2
	fi
    done

    #  Check if disk usage has triggered critical threshold
    percentage=${percentage%\%}
    if [ "$percentage" -ge "$critical_threshold" ]
    then
	echo -n "$mount_point is ${percentage}% full, "
	echo -n "$available$units available. "
	rc=2
	continue
    fi

    #  Check if disk usage has triggered warning threshold
    if [ "$percentage" -ge "$warning_threshold" ]
    then
	echo -n "$mount_point is ${percentage}% full, "
	echo -n "$available$units available. "
	if [ "$rc" -eq 0 ]
	then
	    rc=1
	fi
	continue
    fi
done < $tempfile

if [ "$rc" -eq 0 ]
then
    echo -n 'OK'
fi

echo
exit $rc
