#!/usr/bin/perl
#
# Copyright (C) 2010 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

use 5.010;
use Device::USB::PCSensor::HidTEMPer;

use lib "/usr/lib/nagios/plugins";
use utils qw($TIMEOUT %ERRORS &print_revision &support);

my $pcsensor = Device::USB::PCSensor::HidTEMPer->new();

my $threshold=$ARGV[0];

if(!defined($threshold)) {
    printf "Usage: check_hidtemper TEMP_THRESHOLD\n";
    exit $ERRORS{'CRITICAL'};
}
    
    
if(!$pcsensor->list_devices()) {
    printf "Unable to find temper\n";
    exit $ERRORS{'CRITICAL'};
}

foreach my $device ( $pcsensor->list_devices()) {
    my $temp=$device->internal()->celsius();

    printf "$temp degrees\n";

    if($temp > $threshold) {
	exit $ERRORS{'CRITICAL'};
    }

    exit $ERRORS{'OK'};
}
