#!/bin/bash
#
# Copyright (C) 2012-2013 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

# rsync -av check_host_alive_nrpe_and_icmp monitoringvm1.go-managed.com: && ssh monitoringvm1.go-managed.com time ./check_host_alive_nrpe_and_icmp 195.206.237.208 5% 500 10 500 20

hostaddress=$1
max_loss_percentage=$2
max_rtt_ms=$3
packets=$4
timeout_ms=$5
interval_ms=$6

set -e -o pipefail -o nounset

if [ -z "$hostaddress" -o -z "$max_loss_percentage" -o -z "$max_rtt_ms" -o \
    -z "$packets" -o -z "$timeout_ms" -o -z "$interval_ms" ]
then
    echo "$0: too few argument"
    exit 2
fi

/usr/lib/nagios/plugins/check_nrpe -t 30 -H $hostaddress \
    -c check_nrpe_host_alive -a 'NRPE OK. ' | tr -d "\n"


/usr/lib/nagios/plugins/check_fping $hostaddress \
    -w$max_rtt_ms,$max_loss_percentage \
    -c$max_rtt_ms,$max_loss_percentage \
    -n $packets \
    -i $interval_ms \
    -T $timeout_ms
