#!/bin/sh
#
# Copyright (C) 2010 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

excluded_mountpoints="$*"
rc=0

# Check every ext2, ext3 and ext4 filesystems. Ignore /dev/.static/dev
for dir in $(awk '$2!~/^\/dev\/.static\/dev$/ && /ext[234]/ {print $2}' /proc/mounts)
do
    for excluded_mountpoint in $excluded_mountpoints
    do
	if [ "$dir" = "$excluded_mountpoint" ]
	then
	    continue 2
	fi
    done

    if ! tempfile -d $dir | xargs rm
    then
	rc=2
	echo -n "$dir not mounted rw! "
    fi
done

exit $rc
