#!/bin/sh
#
# Copyright (C) 2009-2012 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

apt_options='-o Debug::NoLocking=true -s -qq'
apt_dir='/var/lib/apt/lists'
critical_rc=2
ok_rc=0

# Check that all packages are up-to-date
tempfile=$(tempfile)
trap "rm -f $tempfile" EXIT HUP INT TRAP TERM
if ! apt-get $apt_options dist-upgrade > $tempfile 2>&1
then
    echo -n "apt-get failed: "
    tr "\n" ' ' < $tempfile
    echo
    exit $critical_rc
fi

packages=$(awk '/^(Inst|Conf) / {print $2}' $tempfile | sort -u | tr "\n" ' ')

if [ -n "$packages" ]
then
    echo "Packages: $packages"
    exit $critical_rc
fi

# Check that APT DB is up-to-date
if [ $(find $apt_dir -mtime 0 | wc -l) = 0 ]
then
    echo "Packages database is obsolete, run apt-get update or install cron-apt"
    exit $critical_rc
fi

# Check that security repository is configured and up-to-date
rc=$critical_rc
for file in /etc/apt/sources.list /etc/apt/sources.list.d
do
    if [ ! -e $file ]
    then
	continue
    fi

    if grep -qr '^deb http.*security' $file &&
	[ $(find $apt_dir -mtime -15 -name 'security*_Packages' | wc -l) -gt 0 ]
    then
	rc=$ok_rc
    fi
done

# Check that APT is not stuck in 'apt-get -f install'. We can't use $apt_options
# because it always returns true with '-s'
if ! apt-get -f -o Debug::NoLocking=true -qq install > $tempfile 2>&1
then
    echo -n "apt-get stuck in -f install: "
    tr "\n" ' ' < $tempfile
    echo
    exit $critical_rc
fi

if [ "$rc" != "$ok_rc" ]
then
    echo 'No security repository in /etc/apt/sources.list or too old security APT cache ! You are probably running an old OS release.'
    exit $critical_rc
fi

echo "OK"
exit $ok_rc
