#!/bin/bash
#
# Copyright (C) 2011 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

url=$1
match=$2
post="$3"

if [ -z "$url" -o -z "$match" ]
then
    echo "$0: Too few argument" >&2
    echo "Usage: $0 URL MATCH [POST_DATA]" >&2
    exit 1
fi

wget='wget -q -T5 -t1 -O-'

if [ ! -z "$post" ]
then
    content=$($wget --post-data="$post" "$url" 2>&1 || true)
else
    content=$($wget "$url" 2>&1 || true)
fi

echo "$content" | tr "\n" " "

if echo "$content" | grep -qE "$match"
then
    exit 0
fi

exit 2
