#!/bin/bash
#
# Copyright (C) 2010-2012 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

excluded_mountpoints="$*"

set -e -o pipefail -o nounset

rc=0
error_msg=''
ok_msg=''

# Check every ext2/3/4 filesystems. Ignore /dev/.static/dev and read only
# mounted devices
mountpoints=$(awk '$2!~/^\/dev\/.static\/dev$/ && \
$4!~/^ro,/ && \
/ext[234]/ {print $2}' /proc/mounts)

for mountpoint in $mountpoints
do
    # Process $excluded_mountpoints filter
    for excluded_mountpoint in $excluded_mountpoints
    do
	if [ "$mountpoint" = "$excluded_mountpoint" ]
	then
	    continue 2
	fi
    done

    # Check if filesystem is writable
    checkdir="$mountpoint"
    if [ -d ${mountpoint%/}/tmp ]
    then
    	checkdir="${mountpoint%/}/tmp"
    fi

    if ! tempfile -d $checkdir 2>/dev/null | xargs -r rm
    then
	rc=2
	error_msg="$mountpoint not mounted rw! $error"
    else
	ok_msg="$mountpoint OK. $ok_msg"
    fi
done

if [ $rc != 0 ]
then
    echo $error_msg
    exit $rc
fi

echo $ok_msg
