#!/bin/bash
#
# Copyright (C) 2013 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#


set -e

warn_threshold=${1/.*/}
crit_threshold=${2/.*/}

if [ -z "$warn_threshold" -o -z "$crit_threshold" ]
then
    echo $0 too few arguments >&2
    echo Usage: $0 WARNING_THRESHOLD CRITICAL_THRESHOLD >&2
    exit 1
fi

total_limit=$(rabbitmqctl status|grep 'total_limit'|tr -d '{}'|cut -d, -f2)
total_used=$(rabbitmqctl status|grep 'total_used'|tr -d '{}'|cut -d, -f2)
fd_used_percent=$(echo "$total_used/$total_limit*100"|bc)


if [ $fd_used_percent -ge $crit_threshold ]

then
    echo "CRIT"
    exit 2
fi

if [ $fd_used_percent -ge $warn_threshold ]
then
    echo "WARN"
    exit 1
fi

echo "OK"
exit 0
