#!/bin/sh
#
# Copyright (C) 2014 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

dnsbls='
sbl.spamhaus.org
xbl.spamhaus.org
pbl.spamhaus.org
zen.spamhaus.org
bl.spamcop.net
cbl.abuseat.org
b.barracudacentral.org
ips.backscatterer.org
opm.tornevall.org
'

critical=0
block=$1
whitelist='/etc/nagios-plugins/config/cyb_rbl.d'

if [ -z "$block" ]
then
    echo $0 too few arguments >&2
    echo Usage: $0 IP_ADDRESS/NETMASK >&2
    exit 1
fi

if ! echo $block|egrep '(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$' > /dev/null
then
    echo $0 $block is not a valid CIDR block
    exit 1
fi

ip_list=$(sipcalc -s 32 $block | awk '/Network/ { print $3 }')

for ip in $ip_list
do
    if ! rgrep -q $ip $whitelist
    then
        revip=$(echo $ip | awk -F. '{print $4"."$3"."$2"."$1}')
        
        for dnsbl in $dnsbls
        do

            if getent hosts $revip.$dnsbl > /dev/null 2>/dev/null
            then   
                echo -n "$ip blacklisted by $dnsbl "
                critical=1
            fi

        done
    fi
done

if [ $critical = 1 ]
then
    echo
    exit 2
fi

echo "OK"
exit 0
