#!/bin/bash
#
# Copyright (C) 2011-2014 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

url=$1
match=$2
post="$3"
header="$4"
fetch_cookie_from_home="$5"

wget='wget -q -T30 -t1 -O- --no-check-certificate'

if [ -z "$url" -o -z "$match" ]
then
    echo "$0: Too few argument" >&2
    echo "Usage: $0 URL MATCH [POST_DATA [HEADERS [FETCH_COOKIE_FROM_HOME]]]" >&2
    exit 1
fi

if [ ! -z "$fetch_cookie_from_home" ]
then
    url_home=$(echo $url | cut -d/ -f1-3)
    header="Cookie: $($wget -S $url_home 2>&1 | awk '/Set-Cookie: .*SESS/ {print $2, $3; exit}')"
fi


if [ ! -z "$post" ]
then
    if [ ! -z "$header" ]
    then
    	content=$($wget --header="$header" --post-data="$post" "$url" 2>&1 || true)
    else
        content=$($wget --post-data="$post" "$url" 2>&1 || true)
    fi
else
    content=$($wget "$url" 2>&1 || true)
fi

# HTTP has the expected content: show the first 200 characters when everything
# is fine
if echo "$content" | grep -qE "$match"
then
    echo "$content" | tr "\n" " " | head -c 200
    exit 0
fi

# HTTP does not have the expected content: show the first 10k characters
echo "$content" | tr "\n" " " | head -c 10000
exit 2
