#!/bin/sh
#
# Copyright (C) 2014 ISVTEC <contact@isvtec.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

worker=$1
app_dir=$2

if [ -z "$worker" -o -z "$app_dir" ]
then
    echo Usage: $0 WORKER APP_DIR
    exit 3
fi

if [ ! -d "$app_dir" ]
then
    echo Cannot access to directory in APP_DIR variable
    exit 3
fi

if [ ! -e "$app_dir/manage.py" ]
then
    echo Cannot find any manage.py file in APP_DIR variable directory
    exit 3
fi

cd $app_dir && ./manage.py celery inspect ping -d $worker|grep -q pong
result=$?

[ ! $result ] && exit 2

echo "$worker: pong!"
exit 0

