#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

rc=0
for mountpoint in $*
do
    if cut -d' ' -f2 /proc/mounts | grep -qE "^$mountpoint$"
    then
	echo -n "$mountpoint OK. "
    else
	rc=2
	echo -n "$mountpoint not mounted. "
    fi

done

echo
exit $rc
