#!/bin/bash
#
# Copyright (C) 2014 Michael Jeanson <michael.jeanson@isvtec.com> 
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.


set -o pipefail -o nounset

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

checkfile='/var/tmp/check_ganeti_cluster_verify'
# seconds
checkfile_max_age="7200"

# File doesn't exist
if [ ! -e "${checkfile}" ]
then
    echo "OK: No output file (${checkfile})"
    exit $STATE_CRITICAL
fi

# File is too old
checkfile_age=$(expr `date +%s` - `stat -c %Y ${checkfile}`)
if [ $checkfile_age -gt $checkfile_max_age ]; then
    echo "Output file from gnt-cluster verify is too old (${checkfile_age} > ${checkfile_max_age})"
    exit $STATE_CRITICAL
fi

# File contains errors
if [ -s "${checkfile}" ]
then
    head -c 1K "${checkfile}" | tr "\n" .
    exit $STATE_CRITICAL
fi

echo "OK"
exit $STATE_OK
