#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

url=$1

set -e -o pipefail -o nounset

# Load API key from configuration file
. /etc/nagios-plugins/config/safe-browsing.conf

if [ -z "$url" -o -z "$api_key" -o -z "$api_url" ]
then
    echo "$0: missing argument"
    exit 2
fi

type=$(wget -q -O- "$api_url&url=$url")

if [ "$type" != '' ]
then
    echo "$url is flagged as $type on Google Safe Browsing"
    exit 2
fi

echo "$url is OK"
