#!/usr/bin/perl
#
# Copyright (C) 2010 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

use 5.010;
use Device::USB::PCSensor::HidTEMPer;

use lib "/usr/lib/nagios/plugins";
use utils qw($TIMEOUT %ERRORS &print_revision &support);

my $pcsensor = Device::USB::PCSensor::HidTEMPer->new();

my $warn=$ARGV[0];
my $critical=$ARGV[1];

if(!defined($warn)) {
    printf "Usage: check_hidtemper <TEMP warn> <TEMP crtitical> \n";
    exit $ERRORS{'CRITICAL'};
}
    
if(!defined($critical)) {
    printf "Usage: check_hidtemper <TEMP warn> <TEMP crtitical> \n";
    exit $ERRORS{'CRITICAL'};
}
    
if(!$pcsensor->list_devices()) {
    printf "Unable to find temper\n";
    exit $ERRORS{'CRITICAL'};
}

foreach my $device ( $pcsensor->list_devices()) {
    my $temp=$device->internal()->celsius();

    printf "Temperature: $temp C | Temperature=$temp" .  "C;25;30;0;50\n";

    if($temp > $critical) {
	exit $ERRORS{'CRITICAL'};
    }

    if($temp > $warn) {
	exit $ERRORS{'WARNING'};
    }

    exit $ERRORS{'OK'};
}
