#!/bin/bash
#
# Copyright (C) 2015 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset
msg='Syslog test'

socket_error='--socket-errors=on'
if dpkg -l bsdutils | grep -qF '2.20'
then
    SOCKET_ERROR=''
fi

if ! timeout 5 logger -i -t $0 -d -p local0.alert "$socket_error" $msg 2>&1
then
    exit 2
fi

echo "Successfully sent message to Syslog"
exit 0
