#!/bin/bash
#
# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

maximum_delay=$1

set -e -o pipefail -o nounset

if [ -z "$maximum_delay" ]
then
    maximum_delay=3600
fi

file=/var/lib/puppet/state/last_run_summary.yaml

if [ ! -f $file ]
then
    echo "$0: $file no such file or directory"
    exit 1
fi

last_run=$(awk '/last_run/ {print $2}' $file)

if [ -z "$last_run" ]
then
    echo "$0: unable to fetch info from $file"
    exit
fi

now=$(date +%s)
time_elapsed=$(($now - $last_run))

if [ $time_elapsed -gt $maximum_delay ]
then
    echo "Puppet was last synced $time_elapsed seconds ago"
    exit 2
fi

echo "OK"
