#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

. /etc/nagios-plugins/config/cyb-sql.conf

threshold=$1

if [ -z "$threshold" ]
then
    echo $0: Too few argument >&2
    echo Usage: $0 CRITICAL_THRESHOLD >&2
    exit 1
fi

SELECT="SELECT COUNT(*)
FROM domains, user
WHERE domains.etat IN (6,9) AND user.etat IN (1,2,6) AND domains.user=user.user"
queue=$(echo $SELECT | $MYSQL)

SELECT="SELECT domains.domain
FROM domains, user
WHERE domains.etat IN (6,9) AND user.etat IN (1,2,6) AND domains.user=user.user
ORDER BY domains.domain"
domains=$(echo $SELECT | $MYSQL | tr "\n" ' ')

echo "$queue domains in registrar queue: $domains"

[ $queue -ge $threshold ] && exit 2

exit 0
