#!/bin/sh
#
# Copyright (C) 2013 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

secret_file="$1"
host="$2"
port="$3"

set -e -o nounset

# Check arguments
if [ -z "$secret_file" -o -z "$host" -o -z "$port" ]
then
    echo "Too few argument. Usage: $0 SECRET_FILE HOST PORT"
    exit 2
fi

# Check file permissions
if [ ! -r $secret_file ]
then
    echo -e "$secret_file is not readable. Fix with 'chgrp nagios $secret_file; chmod g+r $secret_file'"
    exit 2
fi

# Ping Varnish
if varnishadm ping 2>&1
then
    exit 0
fi

exit 2
