#!/bin/bash
#
# Copyright (C) 2011 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -o pipefail

export VTYSH_PAGER=cat

init_routes=$(echo 'show ip ospf neigh' | vtysh ospf | grep -c Init/)

if [ "$init_routes" -gt 0 ]
then
    echo -n "$init_routes routes are in Init state: "
    echo 'show ip ospf neigh' | vtysh ospf | tr "\n" '.'
    exit 2
fi

echo "$init_routes are in Init state"
exit 0
