#!/bin/bash
#
# Copyright (C) 2014 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

host=$1

set -e -o pipefail -o nounset

if [ -z "$host" ]
then
    echo "$0 too few arguments" >&2
    echo "Usage: $0 HOSTNAME" >&2
    exit 2
fi

result_lines=$(ntpdc -n -c monlist $host 2>/dev/null | wc -l)

if [ $result_lines -ne 0 ]
then
    echo "NTP monlist is publicly available and could be used to relay DDOS attacks"
    exit 2
fi

echo "OK"
