#!/bin/bash
#
# Copyright (C) 2014 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

. /etc/ganeti-failover-gateway-node.conf

# Check that the gateway list file is recent
if [ "$(find $gw_file -mmin -60 2>/dev/null | wc -l)" != '1' ]
then
    echo "$gw_file not found or not up-to-date"
    exit 2
fi

echo "$gw_file exists and is up-to-date"
exit 0
