#!/bin/sh
#
# Copyright (C) 2010 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

export PATH=$PATH:/sbin:/usr/sbin

max_offset=2
ntpdate='timeout 10 ntpdate -p1 -q pool.ntp.org'

[ ! -z "$1" ] && max_offset=$1

offset=$($ntpdate | awk '/ time server / {print $10}')

if [ -z "$offset" ]
then
    echo Unable to get time from NTP server
    exit 2
fi

echo $offset sec

# Convert to int
offset=$(echo $offset | cut -d. -f1)

if [ "$offset" -gt $max_offset -o $offset -lt -$max_offset ]
then
    exit 2
fi

exit 0
