#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

RC=0

function check {
    for file in /sys/block/{sd?,vd?}/queue/scheduler
    do
        [ ! -f $file ] && continue

        scheduler=$(grep -c "\[deadline\]" "$file")

        if [ "$scheduler" -ne 1 ]
        then
            echo "No deadline scheduler on $file"
            RC=2
        fi
    done
}

function main {
    check

    if [ "$RC" -eq 0 ]
    then
        echo "All I/O schedulers are set to deadline"
    fi
    exit "$RC"
}

main
