#!/bin/bash
#
# Copyright (C) 2012-2013 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -u -o pipefail

help() {
    echo "Usage: $0 [--hostname=localhost] [--port=11211] [--timeout=5]" >&2
}

# ":" means required
# "::" means optional
TEMP=$(getopt -o h: --long hostname::,port::,timeout:: -n "$0" -- "$@")

# Check for non-GNU getopt
if [ $? != 0 ]
then
    help
    exit 1
fi

# Default values
hostname='localhost'
port=11211
timeout=5
max_connections=1024

# Parse configuration file to fetch max_connection. This is ugly but Memcache
# does not provide any other way to fetch this information.
file='/etc/memcached.conf'
if [ -r "$file" ] && grep -qE '^-c ' $file
then
    max_connections=$(awk '/^-c / {print $2; exit}' $file)
fi

# Parse options with getopt
eval set -- "$TEMP"
while true
do
    case "$1" in
	--hostname)
	    hostname="$2"
	    shift 2
	    ;;

	--port)
	    port="$2"
	    shift 2
	    ;;

	--timeout)
	    timeout="$2"
	    shift 2
	    ;;

	--)
	    shift
	    break
	    ;;

	*)
	    echo "$0: getopt error!" >&2
	    exit 1
	    ;;
    esac
done

tempfile=$(tempfile)
trap "rm -f $tempfile" EXIT HUP INT TRAP TERM

perfdata=''

echo -e "stats\nquit" \
    | timeout $timeout nc -q -1 $hostname $port \
    | tr -d "\r" > $tempfile

# Check the return code
for rc in ${PIPESTATUS[@]}
do
    if [ "$rc" != 0 ]
    then
        echo "Unable to connect to Memcache on $hostname:$port"
	exit 2
    fi
done

limit_maxbytes=0
bytes=0
while read command variable value
do
    if [ "$command" != 'STAT' ]
    then
	continue
    fi

    # Fetch 'bytes' variable
    if [ "$variable" = 'bytes' ]
    then
	bytes=$value
    fi

    # Fetch limit_maxbytes variable
    if [ "$variable" = 'limit_maxbytes' ]
    then
	limit_maxbytes=$value
    fi

    # Fetch curr_connections variable
    if [ "$variable" = 'curr_connections' ]
    then
	curr_connections=$value
    fi

    # Fetch performance data for Nagios
    if [ "$perfdata" = '' ]
    then
	perfdata="$variable=$value"
    else
	perfdata="$perfdata, $variable=$value"
    fi
done < $tempfile

# Check if we use more than 90% of memory
percent_memory_used=$(($bytes * 100 / $limit_maxbytes))
if [ "$percent_memory_used" -ge 90 ]
then
    echo "${percent_memory_used}% memory used, please raise -m option of Memcache"
    exit 2
fi

# Check if we use more than 80% of memory
if [ "$percent_memory_used" -ge 80 ]
then
    echo "${percent_memory_used}% memory used, please raise -m option of Memcache"
    exit 1
fi

# Check if we use more than 90% of memory
percent_connections_used=$(($curr_connections * 100 / $max_connections))
if [ "$percent_connections_used" -ge 90 ]
then
    echo "${percent_connections_used}% connections used, please raise -c option of Memcache"
    exit 2
fi

# Check if we use more than 80% of max_connections
if [ "$percent_connections_used" -ge 80 ]
then
    echo "${percent_connections_used}% connections used, please raise -c option of Memcache"
    exit 1
fi


if [ ! -z "$perfdata" ]
then
    echo -n "OK ${percent_memory_used}% memory used."
    echo " ${percent_connections_used}% connections used | $perfdata"
    exit 0
fi

echo 'Failed to connect Memcache'
exit 2
