#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

subnets=$*

if [ -z "$subnets" ]
then
    echo "$0: Too few arguments!" >&2
    echo "Usage: $0 SUBNET [SUBNET [SUBNET]]" >&2
    echo "Example: $0 10.0.0.0/16" >&2
    exit 1
fi

if /sbin/ip route show $(for subnet in $subnets; do echo "root $subnet "; done) | grep -q weight
then
    echo -n 'Duplicate route: '
    /sbin/ip route show | grep -B1 weight | tr "\n" ' '
    exit 2
fi

echo 'No duplicate route detected'

exit 0
