#!/bin/sh
#
# Copyright (C) 2011 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -o pipefail
rc=0

export PATH=$PATH:/sbin:/usr/sbin

# Check software RAID
for md in /dev/md*
do
    [ ! -e $md -o -d $md ] && continue

    if mdadm --detail --test $md >/dev/null 2>/dev/null
    then
	echo -n "$md: OK. "
    else
	echo -n "$md: "
	mdadm --detail --test $md 2>&1 |grep faulty \
	    | sed -e s/.*faulty/faulty/g | tr -d "\n" || true
	echo -n '. '
	rc=2
    fi
done

# Check mptsas RAID
if which mpt-status >/dev/null && grep -wFq mptsas /proc/modules
then 
    for status in $(mpt-status -s | awk '/^log_id / {print $3}')
    do
	echo -n "MPT status $status. "
	if [ "$status" != 'OPTIMAL' ]
	then
	    rc=2
	fi
    done
fi

# Check mpt2sas RAID
if which sas2ircu >/dev/null && grep -wFq mpt2sas /proc/modules
then
    for status in $(sas2ircu 0 STATUS | awk '/Volume state/ {print $4}')
    do
	echo -n "IRCU status $status. "
	if [ "$status" != 'Optimal' ]
	then
	    rc=2
	fi
    done
fi

# Check 3w_xxxx RAID
if which tw_cli >/dev/null && grep -wFq 3w_xxxx /proc/modules
then
    for status in $(tw-cli /c0 show | awk '/^u/ {print $3}')
    do
	echo -n "3w_xxxx status $status. "
	if [ "$status" != 'OK' ]
	then
	    rc=2
	fi
    done
fi

echo
exit $rc
