#!/bin/sh
#
# Copyright (C) 2011 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -o pipefail
rc=0

# Check software RAID
for md in /dev/md*
do
    [ ! -e $md -o -d $md ] && continue

    if ! mdadm --detail --test $md >/dev/null 2>/dev/null
    then
	mdadm --detail --test $md |grep faulty | sed -e s/.*faulty/faulty/g \
	    | tr "\n" ' ' || true
	rc=2
    fi
done

echo
exit $rc
