#!/bin/bash
#
# Copyright (C) 2012 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

offset_dir=/var/lib/nagios-plugins-cyb

tempfile=$(tempfile)
trap "rm -f $tempfile" EXIT HUP INT TRAP TERM

if logtail2 -f /var/log/kern.log -o $offset_dir/kern.log.offset \
    | grep -F -f /etc/nagios-plugins/config/cyb_check_log.conf > $tempfile
then
    tr "\n" . < $tempfile
    exit 2
fi

echo 'OK'
exit 0
