#!/bin/bash
#
# Copyright (C) 2013 Cyril Bouthors <cyril@boutho.rs>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e -o pipefail -o nounset

for file in /sys/block/sd?/device/queue_depth
do
    [ ! -f $file ] && continue

    read queue_depth < $file

    if [ $queue_depth -le 1 ]
    then
	echo "NCQ not working. Configure the disk controller as AHCI in the BIOS"
	exit 2
    fi
    
done

echo "OK"
