#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

if [ "$1" != "configure" ]
then
    exit 0
fi

file=/etc/sudoers
if ! grep -qE "^nagios " $file
then
    echo nagios ALL=NOPASSWD: /usr/lib/nagios/plugins-cyb/check_smartctl, /usr/bin/jstat, /usr/lib/nagios/plugins-cyb/check_fs_rw, /etc/init.d/apache2, /usr/bin/killall >> $file
fi
