#!/bin/sh
#
# Copyright (C) 2009 Cyril Bouthors <cyril@bouthors.org>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

# Reload NRPE if needed
if which invoke-rc.d >/dev/null 2>&1
then
    invoke-rc.d nagios-nrpe-server reload
else
    /etc/init.d/nagios-nrpe-server reload
fi

if [ "$1" != "configure" ]
then
    exit 0
fi

# Tell sudo to handle /etc/sudoers.d if needed
file=/etc/sudoers
append='#includedir /etc/sudoers.d'
if ! grep -qE "^$append$" $file
then
    echo $append >> $file
fi

# Ensure sudo configuration file permissions are correct
chmod 440 /etc/sudoers.d/nagios-plugins-cyb

# Suppress previous 'nagios' entry from /etc/sudoers
sed -i -e '/^nagios ALL=NOPASSWD: .*nagios.*$/ d' /etc/sudoers

# Create UNIX group if needed
group='ssl-cert'
if ! getent group $group >/dev/null
then
    groupadd $group
fi

# Add 'nagios' user to the 'ssl-cert' group in order for it to check the SSL
# certificates via check_ssl_certs
adduser nagios $group >/dev/null
